travis:
  secure:
    BINSTAR_TOKEN: hqmINj099Nzo+FMtx/Yxj6w8khLVHVcRYSitSH2Z33jbvjTG4s92piSDvfqfLj917bmdE98M8KWhmmDaDn+VKRURIbZo/n3VBZWVxHEUuPx/ZQY0C2qOxV69bJccoV5aOO7Zeqrf1KgN1sP9AbzbxW7WQRM8q/4BxMZkZ6SXP57+mFaN6zaUCjvG3JXkHrJ+CGvLoqWLZAUmMJSlPoeKeHcIEg36Z77xwfyR1fy79KFXXt+AX047vHCvFhKKYVnlrxwGTVQOD2rhV/6PQkg0kpNQmKAr/CQ+kFDHjU4oT07vzocRX1zywU5mHKZ4Tj5NtYrjkdHLC8eTAySe4MdOZO3QtBvQt2FrtxV3C9fAmKP99ABcNTwfsJNLIDAclfhEaC8v7xuRWVpOYxfq34KPF6EZysS7sI1jbpkVFKaoNYgRDN/WNqf1vWJqw5DUUUYzebWiP/RZ34cFCINCkmtiq6BnST8F1cFUgp3KbOawKKbHD60QedYt0kiVo8L+NFxc9T1zUIRX2LkQTsiUm62aqPrQ25VM/euByVFIivP9NZdxJhmp2HdrzlECiTLOwNBbkiSBnYnGGABueuTOOOAbeHx0Xfm8QQGV2yqTDyWy5Dt1TdtlJXCNmBWGClzX4ashyBhWu4AVOsVQYXdrdnQeGpsx5o1+ZmSRzQ5r0IRPCcE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
